plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.3' apply false
    id 'net.neoforged.moddev' version '2.0.141' apply false
}

group = project.group
version = project.version

allprojects {
    repositories {
        mavenCentral()
        maven {
            name = 'Shedaniel'
            url = uri('https://maven.shedaniel.me/')
            mavenContent { includeGroup 'me.shedaniel.cloth' }
        }
        maven {
            name = 'TerraformersMC'
            url = uri('https://maven.terraformersmc.com/')
            mavenContent { includeGroup 'com.terraformersmc' }
        }
        maven {
            name = 'Modrinth'
            url = uri('https://api.modrinth.com/maven')
            mavenContent { includeGroup 'maven.modrinth' }
        }
        maven {
            name = 'Repsy Anvian'
            url = uri('https://maven.anvian.net/releases')
            mavenContent { includeGroup 'net.anvian.anvianslib' }
        }
    }
}

tasks.register('printEnv') {
    doLast {
        def values = [
                MOD_VERSION  : project.version.toString(),
                RELEASE_NAME : "${mod_id}-${project.version}",
                GAME_VERSIONS: minecraft_version_range.toString()
        ]
        values.each { key, value ->
            println "${key}=${value}"
            def githubEnv = System.getenv('GITHUB_ENV')
            if (githubEnv != null) {
                new File(githubEnv).append("${key}=${value}\n")
            }
        }
    }
}
