# Project
version=3.7
group=net.anvian
java_version=25

# Common
minecraft_version=26.1
mod_name=Inventory Tweak
mod_author=anvian
mod_id=inventorytweak
license=GPL-3.0
credits=
description=Fast and easy inventory sorter
minecraft_version_range=[26.1, 26.2)
neo_form_version=26.1-1

# Fabric
fabric_version=0.145.1+26.1
fabric_loader_version=0.19.2

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# Dependencies
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
anvianslib_version=1.5.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false
