# Project
version=3.6
group=net.anvian.inventorytweaks
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Inventory Tweak
mod_author=anvian
mod_id=inventorytweak
license=GPL-3.0
credits=
description=Fast and easy inventory sorter
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050
parchment_minecraft=1.21.11
parchment_version=2025.12.20

# Fabric
fabric_version=0.139.5+1.21.11
fabric_loader_version=0.18.2

# NeoForge
neoforge_version=21.11.3-beta
neoforge_loader_version_range=[4,)

# Dependencies
cloth_config_version=21.11.153
modmenu_version=17.0.0-beta.2
anvianslib_version=1.4
anvianslib_minecraft_version=1.21.10

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
