# Project
version=4.1
group=net.anvian
java_version=25

# Common
minecraft_version=26.2
mod_name=Inventory Tweak
mod_author=anvian
mod_id=inventorytweak
license=GPL-3.0
credits=
description=Fast and easy inventory sorter
minecraft_version_range=[26.2, 26.3)
neo_form_version=26.2-1

# Fabric
fabric_version=0.155.2+26.2
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=26.2.0.7-beta
neoforge_loader_version_range=[4,)

# Dependencies
cloth_config_version=26.2.155
modmenu_version=20.0.1
anvianslib_version=1.5.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false
