name: FabricPublish

on: [ workflow_dispatch ]

env:
  JAVA_VERSION: 21
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
  MODRINTH_ID: jGVzcXaf
  CURSEFORGE_ID: 1068451

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make Gradle Wrapper Executable
        run: chmod +x gradlew

      - name: Set Environment Variables from Gradle
        run: ./gradlew printEnv

      - name: Build
        run: ./gradlew build

      - name: Publish (Modrinth & CurseForge)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ env.MODRINTH_TOKEN }}

          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ env.CURSEFORGE_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar

          name: ${{ env.RELEASE_NAME }}
          version: ${{ env.MOD_VERSION }}
          version-type: 'release'
          changelog-file: CHANGELOG.md

          game-versions: ${{ env.GAME_VERSIONS }}

          loaders: |
            fabric
            quilt

          dependencies: |
            fabric-api
            owo-lib
            anvians-lib

          java: ${{ env.JAVA_VERSION }}
